name: Install Repo
description: Install the toolchain and dependencies

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Personal Access Token (with repo scope)'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Git Credentials
      shell: bash
      run: export GITHUB_TOKEN=${{inputs.GITHUB_TOKEN}}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache NPM modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Install dependencies
      shell: bash
      run: |
        sed -i "s|github:pauchiner/sinjs|https://${{secrets.GITHUB_TOKEN}}@github.com/pauchiner/sinjs.git|" package.json
      run: npm ci
